security:
    password_hashers:
        # Use native password hasher, which auto-selects and migrates the best
        # possible hashing algorithm (which currently is "bcrypt")
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'mail'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/add$, roles: PUBLIC_ACCESS }
        - { path: ^/user*, roles: ROLE_USER }
        - { path: ^/admin*, roles: ROLE_ADMIN }
